[package]
name = "bezier"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.7.3", package = "gtk4", features = ["v4_8"] }
num = "0.4.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
